# Generated by Django 4.2.2 on 2023-10-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RegisterTotalDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("part_of_day", models.CharField(max_length=3)),
                ("is_holiday", models.BooleanField(default=False)),
                ("is_weekend", models.BooleanField(default=False)),
                ("is_promotionday", models.BooleanField(default=False)),
                (
                    "number_vehicles",
                    models.IntegerField(verbose_name="cantidad de vehiculos"),
                ),
                ("temperature", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True, verbose_name="numero")),
                ("location", models.CharField(max_length=45, verbose_name="ubicacion")),
                ("state", models.BooleanField(verbose_name="estado")),
                (
                    "sensor",
                    models.CharField(
                        max_length=45, unique=True, verbose_name="numero sensor"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("carro", "carro"), ("moto", "moto")], max_length=45
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=45, verbose_name="marca")),
                ("model", models.CharField(max_length=45, verbose_name="modelo")),
                ("color", models.CharField(max_length=45)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("carro", "carro"), ("moto", "moto")], max_length=45
                    ),
                ),
                ("placa", models.CharField(max_length=45, unique=True)),
                ("year", models.IntegerField(verbose_name="año del vehiculo")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="dueño",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_entry", models.TimeField(auto_now_add=True)),
                ("time_departure", models.TimeField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="prk.vehicle",
                        verbose_name="vehiculo",
                    ),
                ),
            ],
        ),
    ]
