export const listColorV = [
  { value: 'negro', label: 'Negro' },
  { value: 'blanco', label: 'Blanco' },
  { value: 'rojo', label: 'Rojo' },
  { value: 'azul', label: 'Azul' },
  { value: 'verde', label: 'Verde' },
  { value: 'amarillo', label: 'Amarillo' },
  { value: 'gris', label: 'Gris' },
  { value: 'plateado', label: 'Plateado' },
  { value: 'azul marino', label: 'Azul Marino' },
  { value: 'negro mate', label: 'Negro Mate' },
  { value: 'blanco perla', label: 'Blanco Perla' },
  { value: 'rojo cereza', label: 'Rojo Cereza' },
  { value: 'verde oliva', label: 'Verde Oliva' },
  { value: 'amarillo mostaza', label: 'Amarillo Mostaza' },
  { value: 'gris plata', label: 'Gris Plata' },
  { value: 'azul cielo', label: 'Azul Cielo' },
  { value: 'naranja', label: 'Naranja' },
  { value: 'morado', label: 'Morado' },
  { value: 'marrón', label: 'Marrón' },
  { value: 'rosa', label: 'Rosa' },
  { value: 'turquesa', label: 'Turquesa' },
  { value: 'dorado', label: 'Dorado' },
  { value: 'bronce', label: 'Bronce' },
  { value: 'gris oscuro', label: 'Gris Oscuro' },
  { value: 'verde lima', label: 'Verde Lima' },
  { value: 'azul eléctrico', label: 'Azul Eléctrico' },
  { value: 'rojo oscuro', label: 'Rojo Oscuro' },
  { value: 'negro brillante', label: 'Negro Brillante' },
  { value: 'blanco nieve', label: 'Blanco Nieve' },
  { value: 'otro', label: 'Otro' }
];
export const listTypesV = [
  { value: 'automovil', label: 'Automovil' },
  { value: 'camioneta', label: 'Camioneta' },
  { value: 'furgoneta', label: 'Furgoneta' },
  { value: 'motocicleta', label: 'Motocicleta' }
];
export const listBrandVCarro = [
  { value: 'great-wall', label: 'Great Wall' },
  { value: 'byd', label: 'BYD' },
  { value: 'chery', label: 'Chery' },
  { value: 'geely', label: 'Geely' },
  { value: 'jac', label: 'JAC' },
  { value: 'lifan', label: 'Lifan' },
  { value: 'haval', label: 'Haval' },
  { value: 'zotye', label: 'Zotye' },
  { value: 'jac', label: 'JAC' },
  { value: 'baic', label: 'BAIC' },
  { value: 'byd', label: 'BYD' },
  { value: 'landwind', label: 'Landwind' },
  { value: 'ford', label: 'Ford' },
  { value: 'chevrolet', label: 'Chevrolet' },
  { value: 'volkswagen', label: 'Volkswagen' },
  { value: 'bmw', label: 'BMW' },
  { value: 'mercedes-benz', label: 'Mercedes-Benz' },
  { value: 'audi', label: 'Audi' },
  { value: 'hyundai', label: 'Hyundai' },
  { value: 'kia', label: 'Kia' },
  { value: 'subaru', label: 'Subaru' },
  { value: 'volvo', label: 'Volvo' },
  { value: 'jeep', label: 'Jeep' },
  { value: 'lexus', label: 'Lexus' },
  { value: 'cadillac', label: 'Cadillac' },
  { value: 'buick', label: 'Buick' },
  { value: 'tesla', label: 'Tesla' },
  { value: 'gmc', label: 'GMC' },
  { value: 'ram', label: 'RAM' },
  { value: 'chrysler', label: 'Chrysler' },
  { value: 'fiat', label: 'FIAT' },
  { value: 'jaguar', label: 'Jaguar' },
  { value: 'land rover', label: 'Land Rover' },
  { value: 'porsche', label: 'Porsche' },
  { value: 'mini', label: 'MINI' },
  { value: 'maserati', label: 'Maserati' },
  { value: 'acura', label: 'Acura' },
  { value: 'infiniti', label: 'Infiniti' },
  { value: 'mitsubishi', label: 'Mitsubishi' },
  { value: 'genesis', label: 'Genesis' },
  { value: 'otro', label: 'Otro' }
];
export const listBrandVMoto = [
  { value: 'honda', label: 'Honda' },
  { value: 'kawasaki', label: 'Kawasaki' },
  { value: 'harley-davidson', label: 'Harley-Davidson' },
  { value: 'ducati', label: 'Ducati' },
  { value: 'bmw-motorrad', label: 'BMW Motorrad' },
  { value: 'triumph', label: 'Triumph' },
  { value: 'ktm', label: 'KTM' },
  { value: 'aprilia', label: 'Aprilia' },
  { value: 'moto-guzzi', label: 'Moto Guzzi' },
  { value: 'royal-enfield', label: 'Royal Enfield' },
  { value: 'bajaj', label: 'Bajaj' },
  { value: 'tvS', label: 'TVS' },
  { value: 'hero', label: 'Hero' },
  { value: 'um-motorcycles', label: 'UM Motorcycles' },
  { value: 'zongshen', label: 'Zongshen' },
  { value: 'loncin', label: 'Loncin' },
  { value: 'cfmoto', label: 'CFMoto' },
  { value: 'jinan-qingqi', label: 'Jinan Qingqi' },
  { value: 'suzuki', label: 'Suzuki' },
  { value: 'yamaha', label: 'Yamaha' },
  { value: 'keeway', label: 'Keeway' },
  { value: 'sym', label: 'SYM' },
  { value: 'benelli', label: 'Benelli' },
  { value: 'kymco', label: 'KYMCO' },
  { value: 'igm', label: 'IGM' },
  { value: 'sukida', label: 'SUKIDA' },
  { value: 'shineray', label: 'Shineray' },
  { value: 'motor1', label: 'Motor1' },
  { value: 'otra', label: 'Otra' }
];
